version: "3"

services:
  luizalabs:
    build: .
    ports:
      - "3001:3001"
    container_name: luizalabs
    hostname: luizalabs
    depends_on:
      - db
    command: npm start
    environment:
      - DB_HOST=db
      - DB_USER=luizalabs
      - DB_PASS=luizalabs
      - DB_NAME=luizalabs
  db:
    image: postgres
    ports:
      - "5432:5432"
    container_name: db
    hostname: db
    environment:
      - POSTGRES_DBNAME=luizalabs
      - POSTGRES_USER=luizalabs
      - POSTGRES_PASS=luizalabs
